import {
  AMA,
  Aimee,
  Akinola,
  EUA,
  Irep,
  LBC,
  LogoAMA,
  LogoAimee,
  LogoAkinola,
  LogoEUA,
  LogoIrep,
  LogoLBC,
  LogoSGBC,
  SGBC,
} from "@/assets";

// akinola, aimee, anu, ekom, sgbc, lbc, irep, irep 2, foodbridge, colonees,
export const Projects = [
  {
    id: "2",
    name: "Early Childhood Learning",
    desc: "Anuoluwapo is a distinguished Early Childhood Educator, boasting of over a decade of experience in the classroom and a certification in Elocution. She harbors a deep-seated passion for guiding children towards their utmost potential.",
    image: AMA,
    logo: LogoAMA,
    slug: "early-childhood-learning",
    stack: [
      "mailchimp",
      "zustand",
      "mongoose",
      "uploadthing",
      "nextjs",
      "axios",
      "typescript",
      "vercel",
      "google-recaptcha",
    ],
    liveSite: "https://anuoluwapomichaelayeni.com",
    github: "https://github.com/ekygabriel/ama-edu",
    images: [],
    more: [
      "The most difficult aspect of this project was pulling off this design. This made me delve deep into the nitty-gritties of CSS.In the end it was worth the stress.",
      "This web app was built for a teacher, that intends to promote her courses and educate early years learners and their parents on the current trends in the early childhood education space.",
      "I also built an admin dashboard where the site owner was able to Create, Read, Update and Delete blogs, courses and resources for parents. I also worked with the mailchimp api in this project, which was my first time.",
    ],
  },
  {
    id: "1",
    name: "Institute Of Registered Exercise Professionals",
    desc: "The first of its kind, this Institute was established with the help of Internationally recognized Fitness & Health Professionals to Train & Certify Exercise Professionals as well as accredit Gym facilities in Nigeria. It is Europe Active Accredited.",
    image: Irep,
    logo: LogoIrep,
    slug: "irep",
    stack: [
      "redux-toolkit",
      "mongoose",
      "cloudinary",
      "nextjs",
      "axios",
      "nodemailer",
      "typescript",
      "vercel",
      "rapid-api",
      "google-recaptcha",
    ],
    liveSite: "https://www.ireplearning.com.ng/",
    github: "",
    images: [],
    more: [
      "This is an e-commerce site built for The Institute of Exercise Professionals, a fitness and wellness company in Lagos, Nigeria. The app is designed for both experienced and intending fitness trainers to purchase courses. The unique challenge I faced here was the highly logical pricing.",
      "A course can be unavailable online and be available offline or vice-versa. A course could be free or paid for. A course could have discount or not. If I were to hard-code these, it would not have been that challenging. The challenge is using JUST ONE component, which really helped me logically.",
      "I also built a dashboard where authenticated staff of the company can monitor sales, create, edit or deleted courses and approve sales.",
    ],
  },
  {
    id: "4",
    name: "EkomObong Udo-Affah's Portfolio",
    desc: "EkomObong Udo-Affah is a multifaceted designer specializing in UX, architecture, and graphics. Passionate about human-centered design, I'm on a journey to become Nigeria's top UX Designer.",
    image: EUA,
    logo: LogoEUA,
    slug: "eua",
    stack: [
      "typescript",
      "nextjs",
      "nodemailer",
      "zustand",
      "sass",
      "css modules",
    ],
    liveSite: "https://eua.vercel.app/",
    github: "https://github.com/ekygabriel/my-portfolio",
    images: [],
    more: [
      "This web app was very challenging, the design especially!!! I also had to learn how to statically generate data at build time.",
      'I also had to learn how to add animation transitions on when a user clicks from one page to another using the new "template.tsx" file in the app router.',
    ],
  },

  {
    id: "3",
    name: "Sovereign Grace Bible Church",
    desc: "SGBC is a Confessional Reformed Baptist Church which subscribes to the 1689 London Baptist Confession of Faith. She is regulated both in doctrine and practice by a faithful exposition of the Word of God.",
    image: SGBC,
    logo: LogoSGBC,
    slug: "sgbc",
    stack: [
      "redux-toolkit",
      "mongoose",
      "cloudinary",
      "nextjs",
      "axios",
      "nodemailer",
      "typescript",
      "vercel",
      "rapid-api",
      "google-recaptcha",
    ],
    liveSite: "https://www.sgbc.ng/",
    github: "",
    images: [],
    more: [
      "This project for Sovereign Grace Bible Church, which is one of the reformed baptist churches in Nigeria, was a collaborative one. I worked on the frontend consuming APIs already provided.",
      "Sovereign Grace Bible Church is one of the reformed baptist churches in Nigeria, a congregation that holds to the Reformed Baptist tradition. Our core belief is anchored in the grace of God, affirming that salvation is bestowed solely by grace alone, through faith alone in our Lord Jesus Christ alone to the glory of God alone, according to scriptures alone — this is the heart of Calvinistic soteriology, which we embrace with conviction. we also typically affirm the Baptist distinctive of believer's baptism by immersion.",
      "We also built an admin section where sermons are uploaded, announcements are made, basically, a full-fledged admin dashboard",
    ],
  },

  {
    id: "5",
    name: "Michael Akinola's Portfolio",
    desc: "Michael Akinola is a data scientist, currently deploying advanced data analytics techniques and machine learning algorithms to build predictive models for real world applications.",
    image: Akinola,
    logo: LogoAkinola,
    slug: "michael-akinola",
    stack: [
      "nextjs",
      "tiptap editor",
      "mongoose",
      "axios",
      "redux-toolkit",
      "nodemailer",
      "cloudinary",
    ],
    more: [
      "This web application was made to show the projects made by Michael Akinola, a data scientist based in Indiana, USA. He also writes blogs about Data Analysis, Machine learning and Python on this web app.",
      'This application was initially built with a Node.js backend and Next.js front end. I later changed it to a Next.js full stack app. The most challenging part of this application is the implementation of "likes" without authentication. Here was what I did...',
      "Whenever visitors like a post, a random but unique string is generated by the app and saved on their browsers. This prevents a (regular) user from liking a post more than once. This is not a very efficient solution though, but the best I could come up with based on the circumstance. The best solution in my opinion would be to have the users logged in before they can like. However, the customer did not want logged in users for now.",
    ],
    liveSite: "https://michaelakinola.com",
    github: "https://github.com/thecodingpastor/v2-akinola",
    images: [],
  },
  {
    id: "6",
    name: "Aimee Property Services",
    desc: "Aimee Property Services is an integrated real estate services company with core business activities in Facilities Management, Property Management, Property Sales and Letting Real Estate Consultancy/Advisory.",
    image: Aimee,
    logo: LogoAimee,
    slug: "aimee",
    liveSite: "https://aimeepropertyservices.com/",
    github: "https://github.com/thecodingpastor/aimee",
    images: [],
    stack: ["typescript", "nextjs", "sass", "vercel", "emailjs", "css modules"],
    more: [
      "This website was built for Aimee Property Services, a real estate company in Lagos, Nigeria. It is a minimalistic website. Visitors can send email messages using emailjs package when they submit the contact form.",
      "The most challenging part of this one-page website is the implementing the various UIs. The parallax is a tricky feature to implement if you want it to work on iOS. I had to work with some blurs and rotate properties in css. All in all, it was relatively easy to accomplish.",
    ],
  },
  {
    id: "7",
    name: "Lagos Bible Conference",
    desc: "The Lagos Bible Conference (LBC) is the annual flagship conference of Sovereign Grace Bible Church (and partners) dedicated to promoting the Bible as God's inerrant and infallible Word through a faithful exposition of it.",
    image: LBC,
    logo: LogoLBC,
    slug: "lbc",
    liveSite: "https://lagosbibleconference.com/",
    github: "https://github.com/thecodingpastor/aimee",
    images: [],
    stack: [
      "typescript",
      "nextjs",
      "sass",
      "vercel",
      "youtube-api-v3",
      "css modules",
    ],
    more: [
      "The Lagos Bible Conference's website was built with nextjs and typescript and currently hosted on vercel. It is a website that really stretch me for speed as I was on the clock to get the done. The duration needed for it to be completed was two weeks.",
      "The most challenging part of this website was meeting up with the time line. Thankfully, I did not have to handle the registration for the conference. A third party service, evenito, was employed.",
    ],
  },
];
