import {
  AMA,
  Aimee,
  Akinola,
  EUA,
  FoodBridge,
  FoodBridgeLogo,
  Irep,
  LBC,
  LogoAMA,
  LogoAimee,
  LogoAkinola,
  LogoEUA,
  LogoIrep,
  LogoLBC,
  LogoSGBC,
  SGBC,
  TeamBonding,
  TeamBondingLogo,
  Algokids,
  AlgorithmicsLogo,
  Cornerstone,
  CornerstoneLogo,
  Cropsafe,
  WeMove,
  WeMoveLogo,
  ItsLearningTime,
  ItsLearningTimeLogo,
  CropsafeLogo,
} from "@/assets";

export const Projects = [
  {
    id: "0",
    name: "It's Learning Time",
    desc: "ItsLearningTime equip learners for global excellence through our expert tutors and resources to provide personalised learning tailored to the unique needs of each age group, while our built-in progress tracking and engaging quizzes ensure learning is continuously monitored and adapted to support every child's growth.",
    image: ItsLearningTime,
    logo: ItsLearningTimeLogo,
    slug: "its-learning-time",
    stack: [
      "sveltekit",
      "zustand",
      "shadcn-ui",
      "tailwind",
      "typescript",
      "golang",
      "postgresql",
      "docker",
    ],
    liveSite: "https://itslearningtime.org/",
    github: "",
    images: [],
    more: [
      "This is a fast growing start-up and I am one of the co-founders. Our aim is to make high quality education available to all African children for next to nothing (or at no cost at all).",
      "This is one of the biggest apps I have ever built. It has a separated frontend and backend. The frontend technology includes sveltekit, shadcn-ui, tailwind and vanilla CSS. I tried to use as little libraries as possible to make sure our users do not download so much junk thereby increasing the overall speed of the website.",
      "I used only golang, postgres and docker to host my backend api. For now it is still a monolith, and I believe its going to be a for a long while. Security was at the top of my list when writing this backend. Overall, it has been an enjoyable ride for me to see people all over the world use a product that I wrote from start from finish, front to back.",
    ],
  },
  {
    id: "1",
    name: "Algorithmics Nigeria",
    desc: "Algorithmics is a world-class coding and digital skills programme trusted in over 90 countries, now thoughtfully adapted for Nigerian and African learners. Students gain international-standard skills while learning in a context that feels relevant and practical.",
    image: Algokids,
    logo: AlgorithmicsLogo,
    slug: "algokids",
    stack: [
      "sveltekit",
      "zustand",
      "shadcn-ui",
      "tailwind",
      "typescript",
      "nodejs",
    ],
    liveSite: "https://algorithmics.ng",
    github: "",
    images: [],
    more: [
      "This is a monorepo full stack app that has admin dashboard access for the owners of the web app. This powers the content of the website.",
      "I was able to set up the app from scratch with husky, eslint and a few safety guards to minimize errors to the bearest minimum. I used sveltekit and tailwind and PostgreSQL with Drizzle ORM.",
      "This was my first time trying to replicate an app that already has same brand in other countries of the world. So I was able to learn how things are done in other franchises of the same product, giving me a local insight to a global product.",
    ],
  },
  {
    id: "2",
    name: "Foodbridge",
    desc: "FoodBridge is your ultimate destination for affordable, top-quality food products. Enjoy 15% lower prices than market rates, swift doorstep delivery, and a wide variety of options. Buy now, pay later available.",
    image: FoodBridge,
    logo: FoodBridgeLogo,
    slug: "foodbridge",
    stack: [
      "nextjs",
      "zustand",
      "react-hook-form",
      "tailwind",
      "typescript",
      "vercel",
      "railway",
      "husky",
      "google-analytics",
    ],
    liveSite: "https://www.foodbridgeng.com",
    github: "",
    images: [],
    more: [
      "The frontend ecommerce section of the foodbridgeng webiste was entirely built by me with next.js 14 and Typescript, as it was previously written in an older version. As at the time it went live, it was the most complex app I had worked on by far. There were countless endpoints to consume, each with its own unique requirements for manipulation of data.",
      "I was able to set up the app from scratch with husky, eslint and a few safety guards to minimize errors to the bearest minimum.",
      "My major take away as a developer building this app was that I built a lot of re-usable react components and applied the best practices in building a modern web app from scratch.",
    ],
  },
  {
    id: "3",
    name: "Team Bonding Nigeria",
    desc: "Team Bonding Nigeria specialize in creating memorable and impactful team bonding experiences for corporate organizations and groups. Our activities are designed to foster collaboration, enhance communication, and build stronger, more cohesive teams.",
    image: TeamBonding,
    logo: TeamBondingLogo,
    slug: "team-bonding-nigeria",
    stack: [
      "zoho mail",
      "zustand",
      "mongoose",
      "shadcn",
      "nextjs",
      "typescript",
      "vercel",
    ],
    liveSite: "https://teambondingnigeria.com",
    github: "https://github.com/thecodingpastor/teambonding",
    images: [],
    more: [
      "This app was built for a health and fitness company whose major business is in organizing retreats and team bonding experiences for medium organizations and large organizations.",
      "Visitors to this website can view different bonding packages and categories. The can also view the public images of these events. There is also an also an admin login dashboard where the admin can upload images and descriptions of events.",
      "My major achievement as a developer building this app was that I built a re-usable react component for animations, so all the animations on this website were built without any framework.",
    ],
  },
  {
    id: "4",
    name: "Cornerstone Analytics",
    desc: "Our flagship service, Fractional CDO-as-a-Service, gives executive-level digital leadership without the full-time cost - aligning strategy, data stack, and teams to drive measurable outcomes. Beyond strategy, we equip people through targeted analytics and AI training, ensuring insights turn into lasting habits. ",
    image: Cornerstone,
    logo: CornerstoneLogo,
    slug: "cornerstone-analytics",
    stack: ["tailwind", "zustand", "shadcn-ui", "typescript", "vercel"],
    liveSite: "https://teamcornerstone.io",
    github: "",
    images: [],
    more: [
      "This app was built to showcase the importance of a fractional Chief Digital Officer in a 21st century company. I helped me understand why I might need an F-CDO in my company in the future.",
      "I built it with sveltekit (which is becoming my favourite JavaScript frame-work in the latter part of 2025) and tailwind. It is currently deployed on vercel",
      "What I learnt the most building this app was sourcing for assets (which is tedious by the way - kudos to designers). I was able to filter through the internet to know which is free to use.",
    ],
  },
  {
    id: "5",
    name: "Cropsafe",
    desc: "Cropsafe Agro Services is a fast-growing post-harvest loss management and processing company dedicated to strengthening local agricultural value chains. We focus on palm kernel, shea nut, soybean, and beans processing — driving sustainable job creation, productivity, community impact, and scalable market access.",
    image: Cropsafe,
    logo: CropsafeLogo,
    slug: "cropsafe",
    stack: [
      "sveltekit",
      "zustand",
      "shadcn-ui",
      "tailwind",
      "typescript",
      "vercel",
    ],
    liveSite: "https://www.wemovesummit.com/",
    github: "",
    images: [],
    more: [
      "This is a monorepo full stack app that has admin dashboard access for the owners of the web app. This powers the content of the website.",
      "I was able to set up the app from scratch with husky, eslint and a few safety guards to minimize errors to the bearest minimum. I used sveltekit and tailwind and PostgreSQL with Drizzle ORM.",
      "This was my first time trying to replicate an app that already has same brand in other countries of the world. So I was able to learn how things are done in other franchises of the same product, giving me a local insight to a global product.",
    ],
  },
  {
    id: "6",
    name: "We Move",
    desc: "WeMove Summit is the flagship annual event of the Institute of Exercise Professionals (IEP), created to advance the fitness and wellness industry in Nigeria and beyond. Designed as a premier platform for knowledge exchange, professional recognition, and industry networking, the summit brings together exercise professionals, educators, health experts, and wellness brands under one roof.",
    image: WeMove,
    logo: WeMoveLogo,
    slug: "we-move",
    stack: [
      "sveltekit",
      "zustand",
      "shadcn-ui",
      "tailwind",
      "typescript",
      "vercel",
    ],
    liveSite: "https://www.wemovesummit.com/",
    github: "",
    images: [],
    more: [
      "The WeMove Summit is not just about individual growth, it is about building a stronger, more credible fitness industry that can compete globally while addressing Africa's unique needs.",
      "I built it with sveltekit (which is becoming my favourite JavaScript frame-work in the latter part of 2025) and tailwind. It is currently deployed on vercel",
    ],
  },

  // =============================================================================================================================================================
  {
    id: "7",
    name: "Early Childhood Learning",
    desc: "Anuoluwapo is a distinguished Early Childhood Educator, boasting of over a decade of experience in the classroom and a certification in Elocution. She harbors a deep-seated passion for guiding children towards their utmost potential.",
    image: AMA,
    logo: LogoAMA,
    slug: "early-childhood-learning",
    stack: [
      "mailchimp",
      "zustand",
      "mongoose",
      "uploadthing",
      "nextjs",
      "axios",
      "typescript",
      "vercel",
      "google-recaptcha",
    ],
    liveSite: "https://anuoluwapomichaelayeni.com",
    github: "https://github.com/ekygabriel/ama-edu",
    images: [],
    more: [
      "The most difficult aspect of this project was pulling off this design. This made me delve deep into the nitty-gritties of CSS.In the end it was worth the stress.",
      "This web app was built for a teacher, that intends to promote her courses and educate early years learners and their parents on the current trends in the early childhood education space.",
      "I also built an admin dashboard where the site owner was able to Create, Read, Update and Delete blogs, courses and resources for parents. I also worked with the mailchimp api in this project, which was my first time.",
    ],
  },
  {
    id: "8",
    name: "Institute Of Registered Exercise Professionals",
    desc: "The first of its kind, this Institute was established with the help of Internationally recognized Fitness & Health Professionals to Train & Certify Exercise Professionals as well as accredit Gym facilities in Nigeria. It is Europe Active Accredited.",
    image: Irep,
    logo: LogoIrep,
    slug: "irep",
    stack: [
      "redux-toolkit",
      "mongoose",
      "cloudinary",
      "nextjs",
      "axios",
      "nodemailer",
      "typescript",
      "vercel",
      "rapid-api",
      "google-recaptcha",
    ],
    liveSite: "https://www.ireplearning.com.ng/",
    github: "",
    images: [],
    more: [
      "This is an e-commerce site built for The Institute of Exercise Professionals, a fitness and wellness company in Lagos, Nigeria. The app is designed for both experienced and intending fitness trainers to purchase courses. The unique challenge I faced here was the highly logical pricing.",
      "A course can be unavailable online and be available offline or vice-versa. A course could be free or paid for. A course could have discount or not. If I were to hard-code these, it would not have been that challenging. The challenge is using JUST ONE component, which really helped me logically.",
      "I also built a dashboard where authenticated staff of the company can monitor sales, create, edit or deleted courses and approve sales.",
    ],
  },
  {
    id: "9",
    name: "EkomObong Udo-Affah's Portfolio",
    desc: "EkomObong Udo-Affah is a multifaceted designer specializing in UX, architecture, and graphics. Passionate about human-centered design, I'm on a journey to become Nigeria's top UX Designer.",
    image: EUA,
    logo: LogoEUA,
    slug: "eua",
    stack: [
      "typescript",
      "nextjs",
      "nodemailer",
      "zustand",
      "sass",
      "css modules",
    ],
    liveSite: "https://eua.vercel.app/",
    github: "https://github.com/ekygabriel/my-portfolio",
    images: [],
    more: [
      "This web app was very challenging, the design especially!!! I also had to learn how to statically generate data at build time.",
      'I also had to learn how to add animation transitions on when a user clicks from one page to another using the new "template.tsx" file in the app router.',
    ],
  },

  {
    id: "10",
    name: "Sovereign Grace Bible Church",
    desc: "SGBC is a Confessional Reformed Baptist Church which subscribes to the 1689 London Baptist Confession of Faith. She is regulated both in doctrine and practice by a faithful exposition of the Word of God.",
    image: SGBC,
    logo: LogoSGBC,
    slug: "sgbc",
    stack: [
      "redux-toolkit",
      "mongoose",
      "cloudinary",
      "nextjs",
      "axios",
      "nodemailer",
      "typescript",
      "vercel",
      "rapid-api",
      "google-recaptcha",
    ],
    liveSite: "https://www.sgbc.ng/",
    github: "",
    images: [],
    more: [
      "This project for Sovereign Grace Bible Church, which is one of the reformed baptist churches in Nigeria, was a collaborative one. I worked on the frontend consuming APIs already provided.",
      "Sovereign Grace Bible Church is one of the reformed baptist churches in Nigeria, a congregation that holds to the Reformed Baptist tradition. Our core belief is anchored in the grace of God, affirming that salvation is bestowed solely by grace alone, through faith alone in our Lord Jesus Christ alone to the glory of God alone, according to scriptures alone — this is the heart of Calvinistic soteriology, which we embrace with conviction. we also typically affirm the Baptist distinctive of believer's baptism by immersion.",
      "We also built an admin section where sermons are uploaded, announcements are made, basically, a full-fledged admin dashboard",
    ],
  },

  {
    id: "11",
    name: "Michael Akinola's Portfolio",
    desc: "Michael Akinola is a data scientist, currently deploying advanced data analytics techniques and machine learning algorithms to build predictive models for real world applications.",
    image: Akinola,
    logo: LogoAkinola,
    slug: "michael-akinola",
    stack: [
      "nextjs",
      "tiptap editor",
      "mongoose",
      "axios",
      "redux-toolkit",
      "nodemailer",
      "cloudinary",
    ],
    more: [
      "This web application was made to show the projects made by Michael Akinola, a data scientist based in Indiana, USA. He also writes blogs about Data Analysis, Machine learning and Python on this web app.",
      'This application was initially built with a Node.js backend and Next.js front end. I later changed it to a Next.js full stack app. The most challenging part of this application is the implementation of "likes" without authentication. Here was what I did...',
      "Whenever visitors like a post, a random but unique string is generated by the app and saved on their browsers. This prevents a (regular) user from liking a post more than once. This is not a very efficient solution though, but the best I could come up with based on the circumstance. The best solution in my opinion would be to have the users logged in before they can like. However, the customer did not want logged in users for now.",
    ],
    liveSite: "https://michaelakinola.com",
    github: "https://github.com/thecodingpastor/v2-akinola",
    images: [],
  },
  {
    id: "12",
    name: "Aimee Property Services",
    desc: "Aimee Property Services is an integrated real estate services company with core business activities in Facilities Management, Property Management, Property Sales and Letting Real Estate Consultancy/Advisory.",
    image: Aimee,
    logo: LogoAimee,
    slug: "aimee",
    liveSite: "https://aimeepropertyservices.com/",
    github: "https://github.com/thecodingpastor/aimee",
    images: [],
    stack: ["typescript", "nextjs", "sass", "vercel", "emailjs", "css modules"],
    more: [
      "This website was built for Aimee Property Services, a real estate company in Lagos, Nigeria. It is a minimalistic website. Visitors can send email messages using emailjs package when they submit the contact form.",
      "The most challenging part of this one-page website is the implementing the various UIs. The parallax is a tricky feature to implement if you want it to work on iOS. I had to work with some blurs and rotate properties in css. All in all, it was relatively easy to accomplish.",
    ],
  },
  {
    id: "13",
    name: "Lagos Bible Conference",
    desc: "The Lagos Bible Conference (LBC) is the annual flagship conference of Sovereign Grace Bible Church (and partners) dedicated to promoting the Bible as God's inerrant and infallible Word through a faithful exposition of it.",
    image: LBC,
    logo: LogoLBC,
    slug: "lbc",
    liveSite: "https://lagosbibleconference.com/",
    github: "https://github.com/thecodingpastor/aimee",
    images: [],
    stack: [
      "typescript",
      "nextjs",
      "sass",
      "vercel",
      "youtube-api-v3",
      "css modules",
    ],
    more: [
      "The Lagos Bible Conference's website was built with nextjs and typescript and currently hosted on vercel. It is a website that really stretch me for speed as I was on the clock to get the done. The duration needed for it to be completed was two weeks.",
      "The most challenging part of this website was meeting up with the time line. Thankfully, I did not have to handle the registration for the conference. A third party service, evenito, was employed.",
    ],
  },
];
